[package]
name = "sf"
version = "0.0.1"
authors = ["ky <pupupu0701@gmail.com>"]
edition = "2018"

[dev-dependencies]
tempfile = "3.2.0"

[dependencies]
structopt = "0.3.22"
regex = "1.4.3"
ring = "0.16.19"
rust-crypto = "^0.2"
aes = "0.7.4"
block-modes = "0.8.1"
indicatif = "0.16.2"
